
enum Titles {
    static let plane = "Авиарежим"
    static let wifi = "Wi-fi"
    static let noConnect = "Не подключено"
    static let on = "Вкл."
    static let bluetooth = "Bluetooth"
    static let phone = "Сотовая связь"
    static let modem = "Режим модема"
    static let vpn = "VPN"
    static let notification = "Уведомления"
    static let signals = "Звуки, тактильные сигналы"
    static let worry = "Не беспокоить"
    static let time = "Экранное время"
    static let main = "Основные"
    static let control = "Пункт управления"
    static let screen = "Экран и яркость"
    static let homeScreen = "Экран домой"
    static let access = "Универсальный доступ"
    static let settings = "Settings"
    static let detail = "Detail"
}

enum ImageNames {
    static let plane = "airplane"
    static let wifi = "wifi"
    static let bluetooth = "bluetooth"
    static let phone = "antenna.radiowaves.left.and.right"
    static let modem = "personalhotspot"
    static let vpn = "vpn"
    static let notification = "bell.badge.fill"
    static let signals = "sound"
    static let worry = "moon.fill"
    static let time = "hour"
    static let main = "gear"
    static let notificationImage = "icon-50"
    static let control = "switch.2"
    static let screen = "font"
    static let homeScreen = "house.fill"
    static let access = "figure.stand"
}
